# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 39bf1aa6edd01ce465ad382ccd11bdd33b7f780891403195d5e4a4fe966bc63591e873ff303b21382f1e942e71e472021413c334643a697476b5d117ea074a6f

test:
  secret_key_base: db88b7bcbf0ce6d62b2472402417bd63e1c51f1112b055fb80ddcdace37cfe9ebb127173e18d78753d17ec1c7196b8aac19f2f11a89587d233bb0d4e6f04bedd

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
